# Generated by Django 3.2.7 on 2022-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_auto_20221003_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
